### ISSUE TITLE
Not an issue but a huge thank you.

### ISSUE THREAD

**Issue by tri-c20** [ThisJackRN/i-hate-securly#1]
This method helped me and many others blocking securly. Thank you for this and now I can free browse how I want long with my friends. :)

**Comment by ThisJackRN** [comment]
Hey don't thank me thank  3kh0 https://3kh0.github.io/ext-remover/#ublock-run-run-code-on-pages  Quartinal https://github.com/Quartinal/KillCurly-Working, and Zek-c https://github.com/zek-c/Securly-Kill-V111 I just made it a easier access and understand since the read up is blocked via securly 😭 

(I also fixed a bug that suddenly made the cookies stop working for a bit thats why it just says modified)
