### ISSUE TITLE
A bit wrong

### ISSUE THREAD

**Issue by johndoe6767oops** [ThisJackRN/i-hate-securly#3]
When I close the window It comes back

**Comment by ThisJackRN** [comment]
sorry I should archive this I'm now in college, and I no longer have a school issue Chromebook even to find a new exploit
unlock origin no longer works on Chrome due to Google removing Manifest 2 because of it being able to do more than Manifest 3 like allowing unlock origin to work. Sadly without a Chromebook I cant help.
